### ISSUE TITLE
[3-4 hrs] maintain our existing case studies

### ISSUE THREAD

**Issue by levelos** [thinkshout/thinkshout#352]
Question for @MadouPDX. We have links out there to our existing case studies, although probably not that many. Is it worth leaving them out there but not listed on the work landing page? Not sure what's involved in making them look no terrible in the new template.

**Comment by levelos** [comment]
@MadouPDX and I agree that we need to maintain these

**Comment by levelos** [comment]
Just move them over so we have valid links and the text, clean up post-launch.

**Comment by rosalynhart** [comment]
@levelos  - can you take some of these case studies and Amy can take others? Please let her know which ones you will be working on.

**Comment by rosalynhart** [comment]
Already fixed: Salmon project, Colorado trust, Ocean Outcomes, Lemelson-MIT, SPLC-Selma, SPLC

**Comment by rosalynhart** [comment]
Also @levelos - can you give us clarity on how much cleanup needs to be done?
Example here:
http://thinkshout.github.io/thinkshout/work/edf/
Text is all there and links are there. There are some broken images. 

We've all talked about doing doing the minimum to make these pages functional, but realized that could be defined in more than one way.

**Comment by komejo** [comment]
Note: There is a case study called `template.md` with all of the elements ready to copy/paste.

**Comment by levelos** [comment]
Per our quick chat, fixing broken images by pulling in the ones from the existing site and ensuring the text/links/headers use the global site styles and content is within the right container.

**Comment by rosalynhart** [comment]
Also fixed EDF

**Comment by rosalynhart** [comment]
Per conversation with @levelos - moving other case studies to post-launch work.

**Comment by rosalynhart** [comment]
Also fixed Facing History (the previous case study about that project)

**Comment by rosalynhart** [comment]
Remaining:

- Wild Salmon Center
- Giving Forum
- The Intertwine Alliance
- LAC
- Mailchimp
- Mercy Corps
- MIUSA
- Portland Design Works

@MadouPDX - any of these need to be a priority for next week because you are mentioning them in an NTC talk/sharing them in a presentation soon? After that, any others that are higher priority than others?

**Comment by MadouPDX** [comment]
LAC and Mailchimp should be prioritized for Joe's few hours next week, as those are linked to fairly often.

After that, in order, Mercy Corps, Giving Forum, MIUSA, Intertwine, WSC, PDW. Those can probably wait for the sprint.

**Comment by rosalynhart** [comment]
Thanks @MadouPDX

**Comment by rosalynhart** [comment]
@komejo:
Allocated a couple of hours for you for next week to work on case study cleanup. 
Please start with:

- [ ] LAC

- [ ] MailChimp

Then let's check in and see if we want to do any more or wait on the others till sprint, keeping in mind billable work as a priority. Others will be:

- [ ] Mercy Corps

- [ ] Giving Forum

- [ ] MIUSA

- [ ] Intertwine

- [ ] WSC

- [ ] PDW

**Comment by komejo** [comment]
https://thinkshout.com/work/la-conservancy/
https://thinkshout.com/work/mailchimp/

**Comment by komejo** [comment]
All Case Studies converted and pushed to stage for review: 
 - http://stage.thinkshout.com/work/MIUSA/
 - http://stage.thinkshout.com/work/the-interwine/
 - http://stage.thinkshout.com/work/fip-tracker/
 - http://stage.thinkshout.com/work/ridepdw/

While I was in there I updated the blurb for Giving Forum, it was too long and breaking the layout. Also it was being rendered on the homepage due to index.html using the 'active' switch instead of the 'featured'. This has been fixed, and a limit of three sub-features is also now set. 

Editor guide updated to include Case Studies:  
https://github.com/thinkshout/thinkshout/wiki/Editor-Guide#case-studies

**Comment by komejo** [comment]
Live for some time, closing.
