### ISSUE TITLE
Services Page

### ISSUE THREAD

**Issue by komejo** [thinkshout/thinkshout#724]
## Overview
Update the Service page, consolidating all content into one page with refreshed design for NTC 2019.

## Links
Invision: https://thinkshout.invisionapp.com/share/F3QCZY3ZBDW#/347503117_Services_Desktop_V3
Assets in Drive: https://drive.google.com/drive/folders/1ktHt6cFpitubhfWBkBxiwKnGUePD7ut8

## Dev [4 hrs]
- [x] Consolidate services pages into one page

## Theming [4 hrs]
- [x] Theme hero, sections
- [x] Complete the [Accessibility Testing Checklist](https://github.com/thinkshout/Front-End-Style-Guide/wiki/5.-Testing-tools#accessibility-testing-checklist)

## QA/Client Feedback [2 hrs]

**Comment by vickibrown** [comment]
@brittstetson @komejo Looking great, just a few QA items here:

- [ ] Since the services language is longer, increase the padding beneath that text to match the padding between services sections.
- [ ] Reduce padding between service headlines and body copy by 40%
![screen shot 2019-03-05 at 11 42 30 am](https://user-images.githubusercontent.com/21184833/53832790-ea6ad100-3f3b-11e9-8bd9-d10e2f1b17d5.png)
- [ ] Change paragraph width under services title to match paragraph width of each services section (550 for desktop in the design)
- [ ] The orange word "Bene" should be a different color as it's the Bene brand orange. hex #FF9015
- [ ] Gray Links at the bottom should underline on hover
- [ ] Move "See Us on Github" link to next line since it breaks awkwardly on smaller screens

**Tablet QA (768)**
- [ ] move service titles to above headline like on mobile so there's a 2-column format
- [ ] add 10 pixels of padding between icons and text in bottom sections
- [ ] as mentioned above, CTA links in open source should be on 2 lines
![screen shot 2019-03-05 at 11 41 37 am](https://user-images.githubusercontent.com/21184833/53833221-e25f6100-3f3c-11e9-9eff-c5f6e82a3617.png)

**Mobile QA (768)**
- [ ] Can we keep "Contact us on the same line as let's collaborate?
![screen shot 2019-03-05 at 11 51 28 am](https://user-images.githubusercontent.com/21184833/53833322-15a1f000-3f3d-11e9-83ea-868646857563.png)

**Comment by brittstetson** [comment]
@komejo over to you for QA fixes.

@ThomasKing, can you please add open source language to this ticket.

**Comment by ThomasKing** [comment]
Bene, Code for Good.
Like any effective digital solution, Bene is the answer to a specific problem: Nonprofits with important missions but modest budgets still need to make a big impact through their websites.

Replaces:

Looking for an affordable, out-of-the box website solution? Meet package-deal Bene: an open source platform with strategic support to help meet your organization’s specific needs and goals.



Open Source, for everyone.
The ThinkShout team has invested thousands of hours into helping mission-driven organizations achieve their goals with the help of open source tools, to the point that our contributions now power more than 70,000 websites.

**Comment by komejo** [comment]
QA tweaks done, content updated.

**Comment by ThomasKing** [comment]
Love it, thank you, @komejo ! Those copy blocks look good in there.

**Comment by vickibrown** [comment]
@komejo @brittstetson QA items look good!

**Comment by levelos** [comment]
All set. Note I fixed a couple broken links and removed the legacy _services files.
