### ISSUE TITLE
Footer QA

### ISSUE THREAD

**Issue by vickibrown** [thinkshout/thinkshout#816]
In addition to button color issues on ticket #819 
- [x] Add social icon hover/focus states to hex #F06D2F

**Comment by vickibrown** [comment]
@JulesKhong can you review these before we pass them along to Joe so we can make sure nothing was missed?

**Comment by JulesKhong** [comment]
@vickibrown Reviewed and that was the only thing I could find. @komejo this one is ready for ya

**Comment by JulesKhong** [comment]
- [ ] Make sure the email label color has good color contrast. This is a vanity fix, it just gives us better scores since it's a false flag right now since it's set to visually-hidden, but might as well if you're in there. 
<img width="882" alt="Screen Shot 2020-06-02 at 3 44 52 PM" src="https://user-images.githubusercontent.com/19519395/83577120-424e0a00-a4e8-11ea-9b00-e2ff9277072b.png">

**Comment by komejo** [comment]
Both issues fixed.
